### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by ghost** [Debuggingss/ExampleMod#4]
update java please ♥️

**Comment by Debuggingss** [comment]
Username checks out.

**Comment by ghost** [comment]
asbyth github gone

**Comment by Debuggingss** [comment]
Ah I know what you mean now. I was a little confused about "update java" but I realized you were talking about the java branch. I don't think it's going to get updates anymore so the best thing you can do is copy the build configurations from kotlin branch to your project and be sure to remove kotlin from the plugins and other places.
